export enum Categories {
  NECKLACE = 'NECKLACE',
  BRACELET = 'BRACELET',
  EARRING = 'EARRING',
  ANKLET = 'ANKLET',
  BODY_JEWELLERY = 'BODY_JEWELLERY',
  PHONE_CHARM = 'PHONE_CHARM',
  RING = 'RING',
  MEN_COLLECTION = 'MEN_COLLECTION',
  OTHERS = 'OTHERS',
}
